[build]
  command = "cd personal-portfolio-website && npm install && npm run build"
  publish = "personal-portfolio-website/dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
